# Generated by Django 3.0.3 on 2020-10-03 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('roll', models.IntegerField()),
                ('std', models.TextField(max_length=4)),
                ('email', models.EmailField(max_length=70)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
