# Generated by Django 3.0.3 on 2020-10-03 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myrestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
